//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DesignResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesignResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.Configuration.DesignResou" +
                            "rces", typeof(DesignResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Exception Handling Settings.
        /// </summary>
        internal static string AddExceptionHandlingSettingsCommandTitle {
            get {
                return ResourceManager.GetString("AddExceptionHandlingSettingsCommandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Handler (using type picker).
        /// </summary>
        internal static string CustomHandlerDataAddCommand {
            get {
                return ResourceManager.GetString("CustomHandlerDataAddCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception Handler implemented as a custom class added to Enterprise Library..
        /// </summary>
        internal static string CustomHandlerDataDescription {
            get {
                return ResourceManager.GetString("CustomHandlerDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Exception Handler.
        /// </summary>
        internal static string CustomHandlerDataDisplayName {
            get {
                return ResourceManager.GetString("CustomHandlerDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Custom Exception Handler..
        /// </summary>
        internal static string CustomHandlerDataNameDescription {
            get {
                return ResourceManager.GetString("CustomHandlerDataNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CustomHandlerDataNameDisplayName {
            get {
                return ResourceManager.GetString("CustomHandlerDataNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified type name of the Custom Exception Handler..
        /// </summary>
        internal static string CustomHandlerDataTypeNameDescription {
            get {
                return ResourceManager.GetString("CustomHandlerDataTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string CustomHandlerDataTypeNameDisplayName {
            get {
                return ResourceManager.GetString("CustomHandlerDataTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handles an exception passed to the block and performs an action on it, such as wrapping or logging it, 
        ///and then passes it on to the next exception handler or returns it to the caller..
        /// </summary>
        internal static string ExceptionHandlerDataDescription {
            get {
                return ResourceManager.GetString("ExceptionHandlerDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Handler.
        /// </summary>
        internal static string ExceptionHandlerDataDisplayName {
            get {
                return ResourceManager.GetString("ExceptionHandlerDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Exception Handler..
        /// </summary>
        internal static string ExceptionHandlerDataNameDescription {
            get {
                return ResourceManager.GetString("ExceptionHandlerDataNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ExceptionHandlerDataNameDisplayName {
            get {
                return ResourceManager.GetString("ExceptionHandlerDataNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified type name of the Exception Handler..
        /// </summary>
        internal static string ExceptionHandlerDataTypeNameDescription {
            get {
                return ResourceManager.GetString("ExceptionHandlerDataTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ExceptionHandlerDataTypeNameDisplayName {
            get {
                return ResourceManager.GetString("ExceptionHandlerDataTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration settings for the Exception Handling Application Block..
        /// </summary>
        internal static string ExceptionHandlingSettingsDescription {
            get {
                return ResourceManager.GetString("ExceptionHandlingSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Handling Settings.
        /// </summary>
        internal static string ExceptionHandlingSettingsDisplayName {
            get {
                return ResourceManager.GetString("ExceptionHandlingSettingsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration settings for all Exception Handling Policies..
        /// </summary>
        internal static string ExceptionHandlingSettingsExceptionPoliciesDescription {
            get {
                return ResourceManager.GetString("ExceptionHandlingSettingsExceptionPoliciesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies.
        /// </summary>
        internal static string ExceptionHandlingSettingsExceptionPoliciesDisplayName {
            get {
                return ResourceManager.GetString("ExceptionHandlingSettingsExceptionPoliciesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A policy defines the exceptions it will handle, and the set of Exception Handlers that it will execute when 
        ///one of the specified exceptions is passed to the block..
        /// </summary>
        internal static string ExceptionPolicyDataDescription {
            get {
                return ResourceManager.GetString("ExceptionPolicyDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        internal static string ExceptionPolicyDataDisplayName {
            get {
                return ResourceManager.GetString("ExceptionPolicyDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Exception types configured for the Exception Handling Block..
        /// </summary>
        internal static string ExceptionPolicyDataExceptionTypesDescription {
            get {
                return ResourceManager.GetString("ExceptionPolicyDataExceptionTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Types.
        /// </summary>
        internal static string ExceptionPolicyDataExceptionTypesDisplayName {
            get {
                return ResourceManager.GetString("ExceptionPolicyDataExceptionTypesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Exception Handling Policy..
        /// </summary>
        internal static string ExceptionPolicyDataNameDescription {
            get {
                return ResourceManager.GetString("ExceptionPolicyDataNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ExceptionPolicyDataNameDisplayName {
            get {
                return ResourceManager.GetString("ExceptionPolicyDataNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each Exception Type configured for a policy can specify a series of Exception Handlers that will 
        ///execute when an exception of the specified type is sent to the block for handling by this policy..
        /// </summary>
        internal static string ExceptionTypeDataDescription {
            get {
                return ResourceManager.GetString("ExceptionTypeDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Type.
        /// </summary>
        internal static string ExceptionTypeDataDisplayName {
            get {
                return ResourceManager.GetString("ExceptionTypeDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Exception Handlers configured for this Exception type..
        /// </summary>
        internal static string ExceptionTypeDataExceptionHandlersDescription {
            get {
                return ResourceManager.GetString("ExceptionTypeDataExceptionHandlersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handlers.
        /// </summary>
        internal static string ExceptionTypeDataExceptionHandlersDisplayName {
            get {
                return ResourceManager.GetString("ExceptionTypeDataExceptionHandlersDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Exception..
        /// </summary>
        internal static string ExceptionTypeDataNameDescription {
            get {
                return ResourceManager.GetString("ExceptionTypeDataNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ExceptionTypeDataNameDisplayName {
            get {
                return ResourceManager.GetString("ExceptionTypeDataNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action the Exception Handling Block will take after executing all of the handlers for this Exception type.  
        ///None means that the block will return false to the application allowing it to resume execution. 
        ///NotifyRethrow means that the block will return true to the application, which should re-throw the original exception.
        ///ThrowNewException means that the block will throw the exception that exists after the final handler runs. 
        ///However, if you use the overload of the HandleException method that takes [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExceptionTypeDataPostHandlingActionDescription {
            get {
                return ResourceManager.GetString("ExceptionTypeDataPostHandlingActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post handling action.
        /// </summary>
        internal static string ExceptionTypeDataPostHandlingActionDisplayName {
            get {
                return ResourceManager.GetString("ExceptionTypeDataPostHandlingActionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified type name of the Exception..
        /// </summary>
        internal static string ExceptionTypeDataTypeNameDescription {
            get {
                return ResourceManager.GetString("ExceptionTypeDataTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name.
        /// </summary>
        internal static string ExceptionTypeDataTypeNameDisplayName {
            get {
                return ResourceManager.GetString("ExceptionTypeDataTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces the exception sent to the block with another exception type. 
        ///The message can be specified for the replacement exception type..
        /// </summary>
        internal static string ReplaceHandlerDataDescription {
            get {
                return ResourceManager.GetString("ReplaceHandlerDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Handler.
        /// </summary>
        internal static string ReplaceHandlerDataDisplayName {
            get {
                return ResourceManager.GetString("ReplaceHandlerDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message for the replacement exception..
        /// </summary>
        internal static string ReplaceHandlerDataExceptionMessageDescription {
            get {
                return ResourceManager.GetString("ReplaceHandlerDataExceptionMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Message.
        /// </summary>
        internal static string ReplaceHandlerDataExceptionMessageDisplayName {
            get {
                return ResourceManager.GetString("ReplaceHandlerDataExceptionMessageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key in an external resource file for the localized string to use as the message for the replacement exception. .
        /// </summary>
        internal static string ReplaceHandlerDataExceptionMessageResourceNameDescription {
            get {
                return ResourceManager.GetString("ReplaceHandlerDataExceptionMessageResourceNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Resource Name.
        /// </summary>
        internal static string ReplaceHandlerDataExceptionMessageResourceNameDisplayName {
            get {
                return ResourceManager.GetString("ReplaceHandlerDataExceptionMessageResourceNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the external resource file containing the localized string to use as the message for the replacement exception. .
        /// </summary>
        internal static string ReplaceHandlerDataExceptionMessageResourceTypeDescription {
            get {
                return ResourceManager.GetString("ReplaceHandlerDataExceptionMessageResourceTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Resource Type.
        /// </summary>
        internal static string ReplaceHandlerDataExceptionMessageResourceTypeDisplayName {
            get {
                return ResourceManager.GetString("ReplaceHandlerDataExceptionMessageResourceTypeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Replace Exception Handler..
        /// </summary>
        internal static string ReplaceHandlerDataNameDescription {
            get {
                return ResourceManager.GetString("ReplaceHandlerDataNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ReplaceHandlerDataNameDisplayName {
            get {
                return ResourceManager.GetString("ReplaceHandlerDataNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified type name of the replacement exception..
        /// </summary>
        internal static string ReplaceHandlerDataReplaceExceptionTypeNameDescription {
            get {
                return ResourceManager.GetString("ReplaceHandlerDataReplaceExceptionTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Exception Type .
        /// </summary>
        internal static string ReplaceHandlerDataReplaceExceptionTypeNameDisplayName {
            get {
                return ResourceManager.GetString("ReplaceHandlerDataReplaceExceptionTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified type name of the Replace Exception Handler..
        /// </summary>
        internal static string ReplaceHandlerDataTypeNameDescription {
            get {
                return ResourceManager.GetString("ReplaceHandlerDataTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ReplaceHandlerDataTypeNameDisplayName {
            get {
                return ResourceManager.GetString("ReplaceHandlerDataTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wraps the exception sent to the block as the inner exception of a new exception type. 
        ///The message can be specified for the wrapping exception type..
        /// </summary>
        internal static string WrapHandlerDataDescription {
            get {
                return ResourceManager.GetString("WrapHandlerDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap Handler.
        /// </summary>
        internal static string WrapHandlerDataDisplayName {
            get {
                return ResourceManager.GetString("WrapHandlerDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message for the wrapping exception..
        /// </summary>
        internal static string WrapHandlerDataExceptionMessageDescription {
            get {
                return ResourceManager.GetString("WrapHandlerDataExceptionMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Message.
        /// </summary>
        internal static string WrapHandlerDataExceptionMessageDisplayName {
            get {
                return ResourceManager.GetString("WrapHandlerDataExceptionMessageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key in an external resource file for the localized string to use as the message for the wrapping exception. .
        /// </summary>
        internal static string WrapHandlerDataExceptionMessageResourceNameDescription {
            get {
                return ResourceManager.GetString("WrapHandlerDataExceptionMessageResourceNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Resource Name.
        /// </summary>
        internal static string WrapHandlerDataExceptionMessageResourceNameDisplayName {
            get {
                return ResourceManager.GetString("WrapHandlerDataExceptionMessageResourceNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the external resource file containing the localized string to use as the message for the wrapping exception. .
        /// </summary>
        internal static string WrapHandlerDataExceptionMessageResourceTypeDescription {
            get {
                return ResourceManager.GetString("WrapHandlerDataExceptionMessageResourceTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Resource Type.
        /// </summary>
        internal static string WrapHandlerDataExceptionMessageResourceTypeDisplayName {
            get {
                return ResourceManager.GetString("WrapHandlerDataExceptionMessageResourceTypeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Wrap Exception Handler..
        /// </summary>
        internal static string WrapHandlerDataNameDescription {
            get {
                return ResourceManager.GetString("WrapHandlerDataNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string WrapHandlerDataNameDisplayName {
            get {
                return ResourceManager.GetString("WrapHandlerDataNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified type name of the Wrap Exception Handler..
        /// </summary>
        internal static string WrapHandlerDataTypeNameDescription {
            get {
                return ResourceManager.GetString("WrapHandlerDataTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string WrapHandlerDataTypeNameDisplayName {
            get {
                return ResourceManager.GetString("WrapHandlerDataTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified type name of the wrapping exception..
        /// </summary>
        internal static string WrapHandlerDataWrapExceptionTypeNameDescription {
            get {
                return ResourceManager.GetString("WrapHandlerDataWrapExceptionTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap Exception Type.
        /// </summary>
        internal static string WrapHandlerDataWrapExceptionTypeNameDisplayName {
            get {
                return ResourceManager.GetString("WrapHandlerDataWrapExceptionTypeNameDisplayName", resourceCulture);
            }
        }
    }
}
