//===============================================================================
// Microsoft patterns & practices Enterprise Library
// Policy Injection Application Block
//===============================================================================
// Copyright © Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===============================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.PolicyInjection.CallHandlers.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DesignResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesignResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.PolicyInjection.CallHandlers.Configuration." +
                            "DesignResources", typeof(DesignResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 835 - The name of the authorization provider instance to use. This must map to a configured Authorization Provider instance in the Security Application Block..
        /// </summary>
        internal static string AuthorizationCallHandlerDataAuthorizationProviderDescription {
            get {
                return ResourceManager.GetString("AuthorizationCallHandlerDataAuthorizationProviderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Provider.
        /// </summary>
        internal static string AuthorizationCallHandlerDataAuthorizationProviderDisplayName {
            get {
                return ResourceManager.GetString("AuthorizationCallHandlerDataAuthorizationProviderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 833 - A Call Handler that checks if the current user (the security principal for the current thread) has the requisite permission to access the selected object method or property. This handler uses the Security Application Block to check permissions..
        /// </summary>
        internal static string AuthorizationCallHandlerDataDescription {
            get {
                return ResourceManager.GetString("AuthorizationCallHandlerDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Call Handler.
        /// </summary>
        internal static string AuthorizationCallHandlerDataDisplayName {
            get {
                return ResourceManager.GetString("AuthorizationCallHandlerDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 837 - The name of the Authorization Call Handler..
        /// </summary>
        internal static string AuthorizationCallHandlerDataNameDescription {
            get {
                return ResourceManager.GetString("AuthorizationCallHandlerDataNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string AuthorizationCallHandlerDataNameDisplayName {
            get {
                return ResourceManager.GetString("AuthorizationCallHandlerDataNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 839 - The name of the authorization operation, which may include the tokens {method}, {type}, {namespace}, {assembly}, and {appdomain}..
        /// </summary>
        internal static string AuthorizationCallHandlerDataOperationNameDescription {
            get {
                return ResourceManager.GetString("AuthorizationCallHandlerDataOperationNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Name.
        /// </summary>
        internal static string AuthorizationCallHandlerDataOperationNameDisplayName {
            get {
                return ResourceManager.GetString("AuthorizationCallHandlerDataOperationNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 841 - The position of the handler within the policy handler chain, starting from 1. The default value is zero, which means that there is no explicit order specified for the handler in relation to other handlers in the same handler chain..
        /// </summary>
        internal static string AuthorizationCallHandlerDataOrderDescription {
            get {
                return ResourceManager.GetString("AuthorizationCallHandlerDataOrderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string AuthorizationCallHandlerDataOrderDisplayName {
            get {
                return ResourceManager.GetString("AuthorizationCallHandlerDataOrderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 843 - The fully qualified type name of the Authorization Call Handler..
        /// </summary>
        internal static string AuthorizationCallHandlerDataTypeNameDescription {
            get {
                return ResourceManager.GetString("AuthorizationCallHandlerDataTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string AuthorizationCallHandlerDataTypeNameDisplayName {
            get {
                return ResourceManager.GetString("AuthorizationCallHandlerDataTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 845 - A Call Handler that caches the value or object instance returned from the selected method, or the value of the selected property. .
        /// </summary>
        internal static string CachingCallHandlerDataDescription {
            get {
                return ResourceManager.GetString("CachingCallHandlerDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caching Call Handler.
        /// </summary>
        internal static string CachingCallHandlerDataDisplayName {
            get {
                return ResourceManager.GetString("CachingCallHandlerDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 847 - The length of time from the point when the handler first adds the data to the cache until it expires..
        /// </summary>
        internal static string CachingCallHandlerDataExpirationTimeDescription {
            get {
                return ResourceManager.GetString("CachingCallHandlerDataExpirationTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Time.
        /// </summary>
        internal static string CachingCallHandlerDataExpirationTimeDisplayName {
            get {
                return ResourceManager.GetString("CachingCallHandlerDataExpirationTimeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 849 - The name of the Caching Call Handler..
        /// </summary>
        internal static string CachingCallHandlerDataNameDescription {
            get {
                return ResourceManager.GetString("CachingCallHandlerDataNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CachingCallHandlerDataNameDisplayName {
            get {
                return ResourceManager.GetString("CachingCallHandlerDataNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 851 - The position of the handler within the policy handler chain, starting from 1. The default value is zero, which means that there is no explicit order specified for the handler in relation to other handlers in the same handler chain..
        /// </summary>
        internal static string CachingCallHandlerDataOrderDescription {
            get {
                return ResourceManager.GetString("CachingCallHandlerDataOrderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string CachingCallHandlerDataOrderDisplayName {
            get {
                return ResourceManager.GetString("CachingCallHandlerDataOrderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 853 - The fully qualified type name of the Caching Call Handler..
        /// </summary>
        internal static string CachingCallHandlerDataTypeNameDescription {
            get {
                return ResourceManager.GetString("CachingCallHandlerDataTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string CachingCallHandlerDataTypeNameDisplayName {
            get {
                return ResourceManager.GetString("CachingCallHandlerDataTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 855 - A Call Handler that provides the capability to manage and process exceptions in a standard way. This handler uses the Exception Handling Application Block to handle exceptions raised by the target object..
        /// </summary>
        internal static string ExceptionCallHandlerDataDescription {
            get {
                return ResourceManager.GetString("ExceptionCallHandlerDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Handling Call Handler.
        /// </summary>
        internal static string ExceptionCallHandlerDataDisplayName {
            get {
                return ResourceManager.GetString("ExceptionCallHandlerDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 857 - The name of the exception handling policy to use, as configured in the Exception Handling Application Block..
        /// </summary>
        internal static string ExceptionCallHandlerDataExceptionPolicyNameDescription {
            get {
                return ResourceManager.GetString("ExceptionCallHandlerDataExceptionPolicyNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Policy Name.
        /// </summary>
        internal static string ExceptionCallHandlerDataExceptionPolicyNameDisplayName {
            get {
                return ResourceManager.GetString("ExceptionCallHandlerDataExceptionPolicyNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 859 - The name of the Exception Handling Call Handler..
        /// </summary>
        internal static string ExceptionCallHandlerDataNameDescription {
            get {
                return ResourceManager.GetString("ExceptionCallHandlerDataNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ExceptionCallHandlerDataNameDisplayName {
            get {
                return ResourceManager.GetString("ExceptionCallHandlerDataNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 861 - The position of the handler within the policy handler chain, starting from 1. The default value is zero, which means that there is no explicit order specified for the handler in relation to other handlers in the same handler chain..
        /// </summary>
        internal static string ExceptionCallHandlerDataOrderDescription {
            get {
                return ResourceManager.GetString("ExceptionCallHandlerDataOrderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string ExceptionCallHandlerDataOrderDisplayName {
            get {
                return ResourceManager.GetString("ExceptionCallHandlerDataOrderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 863 - The fully qualified type name of the Exception Handling Call Handler..
        /// </summary>
        internal static string ExceptionCallHandlerDataTypeNameDescription {
            get {
                return ResourceManager.GetString("ExceptionCallHandlerDataTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ExceptionCallHandlerDataTypeNameDisplayName {
            get {
                return ResourceManager.GetString("ExceptionCallHandlerDataTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 865 - A single Category in the list of Categories for the log message..
        /// </summary>
        internal static string LogCallHandlerCategoryEntryDescription {
            get {
                return ResourceManager.GetString("LogCallHandlerCategoryEntryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Entry.
        /// </summary>
        internal static string LogCallHandlerCategoryEntryDisplayName {
            get {
                return ResourceManager.GetString("LogCallHandlerCategoryEntryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 867 - The name of the Category Entry..
        /// </summary>
        internal static string LogCallHandlerCategoryEntryNameDescription {
            get {
                return ResourceManager.GetString("LogCallHandlerCategoryEntryNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LogCallHandlerCategoryEntryNameDisplayName {
            get {
                return ResourceManager.GetString("LogCallHandlerCategoryEntryNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 871 - The message that the Logging Handler will add to the log entry after the target method executes..
        /// </summary>
        internal static string LogCallHandlerDataAfterMessageDescription {
            get {
                return ResourceManager.GetString("LogCallHandlerDataAfterMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After Message.
        /// </summary>
        internal static string LogCallHandlerDataAfterMessageDisplayName {
            get {
                return ResourceManager.GetString("LogCallHandlerDataAfterMessageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 873 - The message that the Logging Handler will add to the log entry before the target method executes..
        /// </summary>
        internal static string LogCallHandlerDataBeforeMessageDescription {
            get {
                return ResourceManager.GetString("LogCallHandlerDataBeforeMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before Message.
        /// </summary>
        internal static string LogCallHandlerDataBeforeMessageDisplayName {
            get {
                return ResourceManager.GetString("LogCallHandlerDataBeforeMessageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 875 - The list of categories to which the Logging Handler will write events. Each category can be a literal value, and/or include the tokens {method}, {type}, {namespace}, and {assembly}..
        /// </summary>
        internal static string LogCallHandlerDataCategoriesDescription {
            get {
                return ResourceManager.GetString("LogCallHandlerDataCategoriesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string LogCallHandlerDataCategoriesDisplayName {
            get {
                return ResourceManager.GetString("LogCallHandlerDataCategoriesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 869 - A Call Handler that provides the capability to write log messages and trace messages as the client code invokes the selected method or accesses the selected property of the target object. This handler uses the Logging Application Block to create and write log messages..
        /// </summary>
        internal static string LogCallHandlerDataDescription {
            get {
                return ResourceManager.GetString("LogCallHandlerDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Call Handler.
        /// </summary>
        internal static string LogCallHandlerDataDisplayName {
            get {
                return ResourceManager.GetString("LogCallHandlerDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 877 - The ID of the event to include in the log message..
        /// </summary>
        internal static string LogCallHandlerDataEventIdDescription {
            get {
                return ResourceManager.GetString("LogCallHandlerDataEventIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Id.
        /// </summary>
        internal static string LogCallHandlerDataEventIdDisplayName {
            get {
                return ResourceManager.GetString("LogCallHandlerDataEventIdDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 879 - Determines whether the call stack will be included in the log message. .
        /// </summary>
        internal static string LogCallHandlerDataIncludeCallStackDescription {
            get {
                return ResourceManager.GetString("LogCallHandlerDataIncludeCallStackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Call Stack.
        /// </summary>
        internal static string LogCallHandlerDataIncludeCallStackDisplayName {
            get {
                return ResourceManager.GetString("LogCallHandlerDataIncludeCallStackDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 881 - Determines whether the duration of the call will be included in After Message section of the log message. .
        /// </summary>
        internal static string LogCallHandlerDataIncludeCallTimeDescription {
            get {
                return ResourceManager.GetString("LogCallHandlerDataIncludeCallTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Call Time.
        /// </summary>
        internal static string LogCallHandlerDataIncludeCallTimeDisplayName {
            get {
                return ResourceManager.GetString("LogCallHandlerDataIncludeCallTimeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 883 - Determines whether the values of the parameters passed to the target method will be included in the log message. .
        /// </summary>
        internal static string LogCallHandlerDataIncludeParameterValuesDescription {
            get {
                return ResourceManager.GetString("LogCallHandlerDataIncludeParameterValuesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Parameter Values.
        /// </summary>
        internal static string LogCallHandlerDataIncludeParameterValuesDisplayName {
            get {
                return ResourceManager.GetString("LogCallHandlerDataIncludeParameterValuesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 885 - Determines if the handler will write log messages before, after, or both before and after the call to the target object. A value from the HandlerLogBehavior enumeration. Valid values are Before, After, and BeforeAndAfter..
        /// </summary>
        internal static string LogCallHandlerDataLogBehaviorDescription {
            get {
                return ResourceManager.GetString("LogCallHandlerDataLogBehaviorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Behavior.
        /// </summary>
        internal static string LogCallHandlerDataLogBehaviorDisplayName {
            get {
                return ResourceManager.GetString("LogCallHandlerDataLogBehaviorDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 887 - The name of the Logging Call Handler..
        /// </summary>
        internal static string LogCallHandlerDataNameDescription {
            get {
                return ResourceManager.GetString("LogCallHandlerDataNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LogCallHandlerDataNameDisplayName {
            get {
                return ResourceManager.GetString("LogCallHandlerDataNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 889 - The position of the handler within the policy handler chain, starting from 1. The default value is zero, which means that there is no explicit order specified for the handler in relation to other handlers in the same handler chain..
        /// </summary>
        internal static string LogCallHandlerDataOrderDescription {
            get {
                return ResourceManager.GetString("LogCallHandlerDataOrderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string LogCallHandlerDataOrderDisplayName {
            get {
                return ResourceManager.GetString("LogCallHandlerDataOrderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 891 - The priority value of the exception  to include in the log message..
        /// </summary>
        internal static string LogCallHandlerDataPriorityDescription {
            get {
                return ResourceManager.GetString("LogCallHandlerDataPriorityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string LogCallHandlerDataPriorityDisplayName {
            get {
                return ResourceManager.GetString("LogCallHandlerDataPriorityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 893 - The severity value of the exception to include in the log message; using values from the TraceEventType enumeration such as Critical, Error, and Warning..
        /// </summary>
        internal static string LogCallHandlerDataSeverityDescription {
            get {
                return ResourceManager.GetString("LogCallHandlerDataSeverityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        internal static string LogCallHandlerDataSeverityDisplayName {
            get {
                return ResourceManager.GetString("LogCallHandlerDataSeverityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 895 - The fully qualified type name of the Logging Call Handler..
        /// </summary>
        internal static string LogCallHandlerDataTypeNameDescription {
            get {
                return ResourceManager.GetString("LogCallHandlerDataTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string LogCallHandlerDataTypeNameDisplayName {
            get {
                return ResourceManager.GetString("LogCallHandlerDataTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 899 - The name of the category of the target performance counter..
        /// </summary>
        internal static string PerformanceCounterCallHandlerDataCategoryNameDescription {
            get {
                return ResourceManager.GetString("PerformanceCounterCallHandlerDataCategoryNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        internal static string PerformanceCounterCallHandlerDataCategoryNameDisplayName {
            get {
                return ResourceManager.GetString("PerformanceCounterCallHandlerDataCategoryNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 897 - A Call Handler that increments a specific counter each time it executes in response to invocation of the selected method or setting of the selected property. This handler uses the instrumentation features that are part of the Enterprise Library Core. .
        /// </summary>
        internal static string PerformanceCounterCallHandlerDataDescription {
            get {
                return ResourceManager.GetString("PerformanceCounterCallHandlerDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Counter Call Handler.
        /// </summary>
        internal static string PerformanceCounterCallHandlerDataDisplayName {
            get {
                return ResourceManager.GetString("PerformanceCounterCallHandlerDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 901 - Whether to increment an &apos;Average duration of each call&apos; counter each time..
        /// </summary>
        internal static string PerformanceCounterCallHandlerDataIncrementAverageCallDurationDescription {
            get {
                return ResourceManager.GetString("PerformanceCounterCallHandlerDataIncrementAverageCallDurationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment Average Call Duration.
        /// </summary>
        internal static string PerformanceCounterCallHandlerDataIncrementAverageCallDurationDisplayName {
            get {
                return ResourceManager.GetString("PerformanceCounterCallHandlerDataIncrementAverageCallDurationDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 903 - Whether to increment a &apos;Number of calls per second&apos; counter each time..
        /// </summary>
        internal static string PerformanceCounterCallHandlerDataIncrementCallsPerSecondDescription {
            get {
                return ResourceManager.GetString("PerformanceCounterCallHandlerDataIncrementCallsPerSecondDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment Calls Per Second.
        /// </summary>
        internal static string PerformanceCounterCallHandlerDataIncrementCallsPerSecondDisplayName {
            get {
                return ResourceManager.GetString("PerformanceCounterCallHandlerDataIncrementCallsPerSecondDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 905 - Whether to increment a &apos;Number of exceptions per second&apos; counter each time..
        /// </summary>
        internal static string PerformanceCounterCallHandlerDataIncrementExceptionsPerSecondDescription {
            get {
                return ResourceManager.GetString("PerformanceCounterCallHandlerDataIncrementExceptionsPerSecondDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment Exceptions Per Second.
        /// </summary>
        internal static string PerformanceCounterCallHandlerDataIncrementExceptionsPerSecondDisplayName {
            get {
                return ResourceManager.GetString("PerformanceCounterCallHandlerDataIncrementExceptionsPerSecondDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 907 - Whether to increment a &apos;Total number of calls&apos; counter each time..
        /// </summary>
        internal static string PerformanceCounterCallHandlerDataIncrementNumberOfCallsDescription {
            get {
                return ResourceManager.GetString("PerformanceCounterCallHandlerDataIncrementNumberOfCallsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment Number Of Calls.
        /// </summary>
        internal static string PerformanceCounterCallHandlerDataIncrementNumberOfCallsDisplayName {
            get {
                return ResourceManager.GetString("PerformanceCounterCallHandlerDataIncrementNumberOfCallsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 909 - Whether to increment a &apos;Total number of exceptions&apos; counter each time..
        /// </summary>
        internal static string PerformanceCounterCallHandlerDataIncrementTotalExceptionsDescription {
            get {
                return ResourceManager.GetString("PerformanceCounterCallHandlerDataIncrementTotalExceptionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment Total Exceptions.
        /// </summary>
        internal static string PerformanceCounterCallHandlerDataIncrementTotalExceptionsDisplayName {
            get {
                return ResourceManager.GetString("PerformanceCounterCallHandlerDataIncrementTotalExceptionsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 911 - The name of the instance of the target performance counter. Can include the tokens {method}, {type}, {namespace}, {assembly}, and {appdomain}..
        /// </summary>
        internal static string PerformanceCounterCallHandlerDataInstanceNameDescription {
            get {
                return ResourceManager.GetString("PerformanceCounterCallHandlerDataInstanceNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Name.
        /// </summary>
        internal static string PerformanceCounterCallHandlerDataInstanceNameDisplayName {
            get {
                return ResourceManager.GetString("PerformanceCounterCallHandlerDataInstanceNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 913 - The name of the Performance Counter Call Handler..
        /// </summary>
        internal static string PerformanceCounterCallHandlerDataNameDescription {
            get {
                return ResourceManager.GetString("PerformanceCounterCallHandlerDataNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PerformanceCounterCallHandlerDataNameDisplayName {
            get {
                return ResourceManager.GetString("PerformanceCounterCallHandlerDataNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 915 - The position of the handler within the policy handler chain, starting from 1. The default value is zero, which means that there is no explicit order specified for the handler in relation to other handlers in the same handler chain..
        /// </summary>
        internal static string PerformanceCounterCallHandlerDataOrderDescription {
            get {
                return ResourceManager.GetString("PerformanceCounterCallHandlerDataOrderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string PerformanceCounterCallHandlerDataOrderDisplayName {
            get {
                return ResourceManager.GetString("PerformanceCounterCallHandlerDataOrderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 917 - The fully qualified type name of the Performance Counter Call Handler..
        /// </summary>
        internal static string PerformanceCounterCallHandlerDataTypeNameDescription {
            get {
                return ResourceManager.GetString("PerformanceCounterCallHandlerDataTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string PerformanceCounterCallHandlerDataTypeNameDisplayName {
            get {
                return ResourceManager.GetString("PerformanceCounterCallHandlerDataTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 919 - Whether to increment a &apos;Total&apos; counter each time..
        /// </summary>
        internal static string PerformanceCounterCallHandlerDataUseTotalCounterDescription {
            get {
                return ResourceManager.GetString("PerformanceCounterCallHandlerDataUseTotalCounterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Total Counter.
        /// </summary>
        internal static string PerformanceCounterCallHandlerDataUseTotalCounterDisplayName {
            get {
                return ResourceManager.GetString("PerformanceCounterCallHandlerDataUseTotalCounterDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 921 - A Call Handler that provides the capability to test whether the value provided for the selected property, or the values specified for the parameters of the selected method, are valid against specific rules. This handler uses the Validation Application Block to perform teh validation..
        /// </summary>
        internal static string ValidationCallHandlerDataDescription {
            get {
                return ResourceManager.GetString("ValidationCallHandlerDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Call Handler.
        /// </summary>
        internal static string ValidationCallHandlerDataDisplayName {
            get {
                return ResourceManager.GetString("ValidationCallHandlerDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 923 - The name of the Validation Call Handler..
        /// </summary>
        internal static string ValidationCallHandlerDataNameDescription {
            get {
                return ResourceManager.GetString("ValidationCallHandlerDataNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ValidationCallHandlerDataNameDisplayName {
            get {
                return ResourceManager.GetString("ValidationCallHandlerDataNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 925 - The position of the handler within the policy handler chain, starting from 1. The default value is zero, which means that there is no explicit order specified for the handler in relation to other handlers in the same handler chain..
        /// </summary>
        internal static string ValidationCallHandlerDataOrderDescription {
            get {
                return ResourceManager.GetString("ValidationCallHandlerDataOrderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string ValidationCallHandlerDataOrderDisplayName {
            get {
                return ResourceManager.GetString("ValidationCallHandlerDataOrderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 927 - The name of the rule set to use for all target object types, as configured in the Validation Application Block. An empty string causes the handler to use the default rule set..
        /// </summary>
        internal static string ValidationCallHandlerDataRuleSetDescription {
            get {
                return ResourceManager.GetString("ValidationCallHandlerDataRuleSetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Set.
        /// </summary>
        internal static string ValidationCallHandlerDataRuleSetDisplayName {
            get {
                return ResourceManager.GetString("ValidationCallHandlerDataRuleSetDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 929 - A value from the SpecificationSource enumeration that defines the locations where the handler will look for validation rules. Valid values are Attributes, Configuration, ParameterAttributesOnly, and Both..
        /// </summary>
        internal static string ValidationCallHandlerDataSpecificationSourceDescription {
            get {
                return ResourceManager.GetString("ValidationCallHandlerDataSpecificationSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Source.
        /// </summary>
        internal static string ValidationCallHandlerDataSpecificationSourceDisplayName {
            get {
                return ResourceManager.GetString("ValidationCallHandlerDataSpecificationSourceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 931 - The fully qualified type name of the Validation Call Handler..
        /// </summary>
        internal static string ValidationCallHandlerDataTypeNameDescription {
            get {
                return ResourceManager.GetString("ValidationCallHandlerDataTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ValidationCallHandlerDataTypeNameDisplayName {
            get {
                return ResourceManager.GetString("ValidationCallHandlerDataTypeNameDisplayName", resourceCulture);
            }
        }
    }
}
