//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.Validation.Integration.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.Validation.Integration.WPF.Properties.Resou" +
                            "rces", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ValidatorRule cannot be updated..
        /// </summary>
        internal static string ExceptionCannotModifyDynamicRule {
            get {
                return ResourceManager.GetString("ExceptionCannotModifyDynamicRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binding with the complex path &apos;{0}&apos; cannot be validated. Only single-property binding paths are supported..
        /// </summary>
        internal static string ExceptionComplexBindingPath {
            get {
                return ResourceManager.GetString("ExceptionComplexBindingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dependency property with name &apos;{0}&apos; for element &apos;{1}&apos; (Name=&apos;{2}&apos;, HashCode={3}) does not have a binding to validate..
        /// </summary>
        internal static string ExceptionDependencyPropertyHasNoBinding {
            get {
                return ResourceManager.GetString("ExceptionDependencyPropertyHasNoBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element &apos;{1}&apos; (Name=&apos;{2}&apos;, HashCode={3}) does not have a dependency property with name &apos;{0}&apos;..
        /// </summary>
        internal static string ExceptionMissingDependencyProperty {
            get {
                return ResourceManager.GetString("ExceptionMissingDependencyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source property name for the ValidatorRule is not set..
        /// </summary>
        internal static string ExceptionSourcePropertyNameNotSet {
            get {
                return ResourceManager.GetString("ExceptionSourcePropertyNameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source type &apos;{0}&apos; does not have a property &apos;{1}&apos; for the ValidatorRule..
        /// </summary>
        internal static string ExceptionSourcePropertyNotFound {
            get {
                return ResourceManager.GetString("ExceptionSourcePropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source type for the ValidatorRule is not set..
        /// </summary>
        internal static string ExceptionSourceTypeNotSet {
            get {
                return ResourceManager.GetString("ExceptionSourceTypeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown binding expression of type &apos;{0}&apos;..
        /// </summary>
        internal static string ExceptionUnexpectedBindingExpression {
            get {
                return ResourceManager.GetString("ExceptionUnexpectedBindingExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve the type from the binding source..
        /// </summary>
        internal static string ExceptionUnexpectedMissingType {
            get {
                return ResourceManager.GetString("ExceptionUnexpectedMissingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve the property from a binding..
        /// </summary>
        internal static string ExceptionUnexpectedPropertyType {
            get {
                return ResourceManager.GetString("ExceptionUnexpectedPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to extract a value from an unknown object..
        /// </summary>
        internal static string ExceptionUnexpectedValueSource {
            get {
                return ResourceManager.GetString("ExceptionUnexpectedValueSource", resourceCulture);
            }
        }
    }
}
