//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.Caching.Configuration.Manageability.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.Caching.Configuration.Manageability.Propert" +
                            "ies.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing store settings.
        /// </summary>
        internal static string BackingStoreSettingsPartName {
            get {
                return ResourceManager.GetString("BackingStoreSettingsPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration poll frequency (secs.).
        /// </summary>
        internal static string CacheManagerExpirationPollFrequencyInSecondsPartName {
            get {
                return ResourceManager.GetString("CacheManagerExpirationPollFrequencyInSecondsPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum elements in cache before scavenging.
        /// </summary>
        internal static string CacheManagerMaximumElementsInCacheBeforeScavengingPartName {
            get {
                return ResourceManager.GetString("CacheManagerMaximumElementsInCacheBeforeScavengingPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number to remove when scavenging.
        /// </summary>
        internal static string CacheManagerNumberToRemoveWhenScavengingPartName {
            get {
                return ResourceManager.GetString("CacheManagerNumberToRemoveWhenScavengingPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify settings for cache manager &apos;{0}&apos;.
        /// </summary>
        internal static string CacheManagerPolicyNameTemplate {
            get {
                return ResourceManager.GetString("CacheManagerPolicyNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache managers.
        /// </summary>
        internal static string CacheManagersCategoryName {
            get {
                return ResourceManager.GetString("CacheManagersCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default cache manager.
        /// </summary>
        internal static string CacheManagerSettingsDefaultCacheManagerPartName {
            get {
                return ResourceManager.GetString("CacheManagerSettingsDefaultCacheManagerPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify settings for caching block.
        /// </summary>
        internal static string CacheManagerSettingsPolicyName {
            get {
                return ResourceManager.GetString("CacheManagerSettingsPolicyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caching.
        /// </summary>
        internal static string CachingSectionCategoryName {
            get {
                return ResourceManager.GetString("CachingSectionCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string CustomProviderAttributesPartName {
            get {
                return ResourceManager.GetString("CustomProviderAttributesPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string CustomProviderTypePartName {
            get {
                return ResourceManager.GetString("CustomProviderTypePartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition name.
        /// </summary>
        internal static string IsolatedStorageCacheStorageDataPartitionNamePartName {
            get {
                return ResourceManager.GetString("IsolatedStorageCacheStorageDataPartitionNamePartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In memory store - no settings.
        /// </summary>
        internal static string NullBackingStoreNoSettingsPartName {
            get {
                return ResourceManager.GetString("NullBackingStoreNoSettingsPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption provider settings.
        /// </summary>
        internal static string StorageEncryptionProviderSettingsPartName {
            get {
                return ResourceManager.GetString("StorageEncryptionProviderSettingsPartName", resourceCulture);
            }
        }
    }
}
