//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string AddCustomHandlerData {
            get {
                return ResourceManager.GetString("AddCustomHandlerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Type.
        /// </summary>
        public static string AddExceptionTypeDisplayName {
            get {
                return ResourceManager.GetString("AddExceptionTypeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new exception type that is handled by this exception policy..
        /// </summary>
        public static string AddExceptionTypeHelpText {
            get {
                return ResourceManager.GetString("AddExceptionTypeHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Info:.
        /// </summary>
        public static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new policy..
        /// </summary>
        public static string AddPolicyDisplayDescription {
            get {
                return ResourceManager.GetString("AddPolicyDisplayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        public static string AddPolicyDisplayName {
            get {
                return ResourceManager.GetString("AddPolicyDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Handler.
        /// </summary>
        public static string AddReplaceHandlerData {
            get {
                return ResourceManager.GetString("AddReplaceHandlerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace the exception with another exception..
        /// </summary>
        public static string AddReplaceHandlerDataDescription {
            get {
                return ResourceManager.GetString("AddReplaceHandlerDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap Handler.
        /// </summary>
        public static string AddWrapHandlerData {
            get {
                return ResourceManager.GetString("AddWrapHandlerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap the exception within another exception..
        /// </summary>
        public static string AddWrapHandlerDataDescription {
            get {
                return ResourceManager.GetString("AddWrapHandlerDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string AttributesDescription {
            get {
                return ResourceManager.GetString("AttributesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string AttributesDisplayName {
            get {
                return ResourceManager.GetString("AttributesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthorizationProviderTypeDescription.
        /// </summary>
        public static string AuthorizationProviderTypeDescription {
            get {
                return ResourceManager.GetString("AuthorizationProviderTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise Library Exception Handling Application Block.
        /// </summary>
        public static string BlockName {
            get {
                return ResourceManager.GetString("BlockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot swallow exceptions for methods with non-null return type..
        /// </summary>
        public static string CantSwallowNonVoidReturnMessage {
            get {
                return ResourceManager.GetString("CantSwallowNonVoidReturnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HANDLING CHAIN EXCEPTION:.
        /// </summary>
        public static string ChainException {
            get {
                return ResourceManager.GetString("ChainException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A configuration failure occurred while creating policy ‘{0}’..
        /// </summary>
        public static string ConfigurationFailureCreatingPolicy {
            get {
                return ResourceManager.GetString("ConfigurationFailureCreatingPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{3}&apos; for custom exception handler with name &apos;{2}&apos; is not a valid type ({0} line {1})..
        /// </summary>
        public static string CustomHandlerInvalidTypeException {
            get {
                return ResourceManager.GetString("CustomHandlerInvalidTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{3}&apos; for custom exception handler with name &apos;{2}&apos; does not have the expected constructor ({0} line {1})..
        /// </summary>
        public static string CustomHandlerMissingConstructorException {
            get {
                return ResourceManager.GetString("CustomHandlerMissingConstructorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{3}&apos; for custom exception handler with name &apos;{2}&apos; is not a valid handler type ({0} line {1})..
        /// </summary>
        public static string CustomHandlerNotHandlerTypeException {
            get {
                return ResourceManager.GetString("CustomHandlerNotHandlerTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The custom exception handler with name &apos;{2}&apos; does not have a type specified ({0} line {1})..
        /// </summary>
        public static string CustomHandlerNoTypeException {
            get {
                return ResourceManager.GetString("CustomHandlerNoTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error occurred while handling an exception for policy &quot;{0}&quot;..
        /// </summary>
        public static string ErrorHandlingExceptionMessage {
            get {
                return ResourceManager.GetString("ErrorHandlingExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event id.
        /// </summary>
        public static string EventIdDisplayName {
            get {
                return ResourceManager.GetString("EventIdDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load the exception handling section from the configuration file..
        /// </summary>
        public static string ExceptionCannotRetrieveConfiguration {
            get {
                return ResourceManager.GetString("ExceptionCannotRetrieveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration section for Exception Handling cannot be found in the configuration source..
        /// </summary>
        public static string ExceptionExceptionHandlingSectionNotFound {
            get {
                return ResourceManager.GetString("ExceptionExceptionHandlingSectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handlers.
        /// </summary>
        public static string ExceptionHandlersDisplayName {
            get {
                return ResourceManager.GetString("ExceptionHandlersDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Handler Type.
        /// </summary>
        public static string ExceptionHandlerTypeDescription {
            get {
                return ResourceManager.GetString("ExceptionHandlerTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Handler Type.
        /// </summary>
        public static string ExceptionHandlerTypeDisplayName {
            get {
                return ResourceManager.GetString("ExceptionHandlerTypeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ExceptionManager for the ExceptionPolicy is already set..
        /// </summary>
        public static string ExceptionManagerAlreadySet {
            get {
                return ResourceManager.GetString("ExceptionManagerAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must set an ExceptionManager in the ExceptionPolicy class using the SetExceptionManager method..
        /// </summary>
        public static string ExceptionManagerNotSet {
            get {
                return ResourceManager.GetString("ExceptionManagerNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception message.
        /// </summary>
        public static string ExceptionMessageDisplayName {
            get {
                return ResourceManager.GetString("ExceptionMessageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception message resource name.
        /// </summary>
        public static string ExceptionMessageResourceNameDisplayName {
            get {
                return ResourceManager.GetString("ExceptionMessageResourceNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception message resource type.
        /// </summary>
        public static string ExceptionMessageResourceTypeDisplayName {
            get {
                return ResourceManager.GetString("ExceptionMessageResourceTypeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to rethrow exception: The exception to throw is null..
        /// </summary>
        public static string ExceptionNullException {
            get {
                return ResourceManager.GetString("ExceptionNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies.
        /// </summary>
        public static string ExceptionPoliciesDisplayName {
            get {
                return ResourceManager.GetString("ExceptionPoliciesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve policy information.
        /// </summary>
        public static string ExceptionPolicyNameInvalid {
            get {
                return ResourceManager.GetString("ExceptionPolicyNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The policy with name &apos;{0}&apos; cannot be found. Exception handling aborted..
        /// </summary>
        public static string ExceptionPolicyNotFound {
            get {
                return ResourceManager.GetString("ExceptionPolicyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception handling configuration does not contain a policy with name &apos;{0}&apos;..
        /// </summary>
        public static string ExceptionPolicyNotFoundInConfigurationException {
            get {
                return ResourceManager.GetString("ExceptionPolicyNotFoundInConfigurationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value can not be an empty string or null..
        /// </summary>
        public static string ExceptionStringNullOrEmpty {
            get {
                return ResourceManager.GetString("ExceptionStringNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type must be of type Exception..
        /// </summary>
        public static string ExceptionTypeNotException {
            get {
                return ResourceManager.GetString("ExceptionTypeNotException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Types.
        /// </summary>
        public static string ExceptionTypesDisplayName {
            get {
                return ResourceManager.GetString("ExceptionTypesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception of type &apos;{0}&apos; occurred and was caught..
        /// </summary>
        public static string ExceptionWasCaught {
            get {
                return ResourceManager.GetString("ExceptionWasCaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access failed.
        /// </summary>
        public static string FieldAccessFailed {
            get {
                return ResourceManager.GetString("FieldAccessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatter type name.
        /// </summary>
        public static string FormatterTypeNameDisplayName {
            get {
                return ResourceManager.GetString("FormatterTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help link : {0}.
        /// </summary>
        public static string HelpLink {
            get {
                return ResourceManager.GetString("HelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Exception.
        /// </summary>
        public static string InnerException {
            get {
                return ResourceManager.GetString("InnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log category.
        /// </summary>
        public static string LogCategoryDisplayName {
            get {
                return ResourceManager.GetString("LogCategoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message : {0}.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be implemented by subclasses.
        /// </summary>
        public static string MustBeImplementedBySubclassException {
            get {
                return ResourceManager.GetString("MustBeImplementedBySubclassException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameDisplayName {
            get {
                return ResourceManager.GetString("NameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFENDING EXCEPTION:.
        /// </summary>
        public static string OffendingException {
            get {
                return ResourceManager.GetString("OffendingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORIGINAL EXCEPTION:.
        /// </summary>
        public static string OriginalException {
            get {
                return ResourceManager.GetString("OriginalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Denied.
        /// </summary>
        public static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POLICY NAME: {0}.
        /// </summary>
        public static string PolicyName {
            get {
                return ResourceManager.GetString("PolicyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post handling action.
        /// </summary>
        public static string PostHandlingActionDisplayName {
            get {
                return ResourceManager.GetString("PostHandlingActionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string PriorityDisplayName {
            get {
                return ResourceManager.GetString("PriorityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access failed.
        /// </summary>
        public static string PropertyAccessFailed {
            get {
                return ResourceManager.GetString("PropertyAccessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace exception type .
        /// </summary>
        public static string ReplaceExceptionTypeNameDisplayName {
            get {
                return ResourceManager.GetString("ReplaceExceptionTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Handling Settings.
        /// </summary>
        public static string SectionDisplayName {
            get {
                return ResourceManager.GetString("SectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        public static string SeverityDisplayName {
            get {
                return ResourceManager.GetString("SeverityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source : {0}.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace.
        /// </summary>
        public static string StackTrace {
            get {
                return ResourceManager.GetString("StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stack trace is unavailable..
        /// </summary>
        public static string StackTraceUnavailable {
            get {
                return ResourceManager.GetString("StackTraceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleDisplayName {
            get {
                return ResourceManager.GetString("TitleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name.
        /// </summary>
        public static string TypeNameDisplayName {
            get {
                return ResourceManager.GetString("TypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type : {0}.
        /// </summary>
        public static string TypeString {
            get {
                return ResourceManager.GetString("TypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to handle exception: &apos;{0}&apos;..
        /// </summary>
        public static string UnableToHandleException {
            get {
                return ResourceManager.GetString("UnableToHandleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;undefined value&gt;.
        /// </summary>
        public static string UndefinedValue {
            get {
                return ResourceManager.GetString("UndefinedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default logger.
        /// </summary>
        public static string UseDefaultLoggerDisplayName {
            get {
                return ResourceManager.GetString("UseDefaultLoggerDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap exception type.
        /// </summary>
        public static string WrapExceptionTypeNameDisplayName {
            get {
                return ResourceManager.GetString("WrapExceptionTypeNameDisplayName", resourceCulture);
            }
        }
    }
}
