//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.PolicyInjection.Configuration.Design.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.PolicyInjection.Configuration.Design.Proper" +
                            "ties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Matching Rule.
        /// </summary>
        internal static string AddAssemblyMatchingRuleCommandText {
            get {
                return ResourceManager.GetString("AddAssemblyMatchingRuleCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Assembly Matching Rule..
        /// </summary>
        internal static string AddAssemblyMatchingRuleCommandTextLong {
            get {
                return ResourceManager.GetString("AddAssemblyMatchingRuleCommandTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Attribute Matching Rule.
        /// </summary>
        internal static string AddCustomAttributeMatchingRuleCommandText {
            get {
                return ResourceManager.GetString("AddCustomAttributeMatchingRuleCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Custom Attribute Matching Rule..
        /// </summary>
        internal static string AddCustomAttributeMatchingRuleCommandTextLong {
            get {
                return ResourceManager.GetString("AddCustomAttributeMatchingRuleCommandTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Policy Injector.
        /// </summary>
        internal static string AddCustomInjectorCommandText {
            get {
                return ResourceManager.GetString("AddCustomInjectorCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Custom Policy Injector.
        /// </summary>
        internal static string AddCustomInjectorCommandTextLong {
            get {
                return ResourceManager.GetString("AddCustomInjectorCommandTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Matching Rule.
        /// </summary>
        internal static string AddCustomMatchingRuleCommandText {
            get {
                return ResourceManager.GetString("AddCustomMatchingRuleCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Custom Matching Rule..
        /// </summary>
        internal static string AddCustomMatchingRuleCommandTextLong {
            get {
                return ResourceManager.GetString("AddCustomMatchingRuleCommandTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Name Matching Rule.
        /// </summary>
        internal static string AddMemberNameMatchingRuleCommandText {
            get {
                return ResourceManager.GetString("AddMemberNameMatchingRuleCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Member Name Matching Rule..
        /// </summary>
        internal static string AddMemberNameMatchingRuleCommandTextLong {
            get {
                return ResourceManager.GetString("AddMemberNameMatchingRuleCommandTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Signature Matching Rule.
        /// </summary>
        internal static string AddMethodSignatureMatchingRuleCommandText {
            get {
                return ResourceManager.GetString("AddMethodSignatureMatchingRuleCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Method Signature Matching Rule..
        /// </summary>
        internal static string AddMethodSignatureMatchingRuleCommandTextLong {
            get {
                return ResourceManager.GetString("AddMethodSignatureMatchingRuleCommandTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace Matching Rule.
        /// </summary>
        internal static string AddNamespaceMatchingRuleCommandText {
            get {
                return ResourceManager.GetString("AddNamespaceMatchingRuleCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Namespace Matching Rule..
        /// </summary>
        internal static string AddNamespaceMatchingRuleCommandTextLong {
            get {
                return ResourceManager.GetString("AddNamespaceMatchingRuleCommandTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Type Matching Rule.
        /// </summary>
        internal static string AddParameterTypeMatchingRuleCommandText {
            get {
                return ResourceManager.GetString("AddParameterTypeMatchingRuleCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Parameter Type Matching Rule..
        /// </summary>
        internal static string AddParameterTypeMatchingRuleCommandTextLong {
            get {
                return ResourceManager.GetString("AddParameterTypeMatchingRuleCommandTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        internal static string AddPolicyCommandText {
            get {
                return ResourceManager.GetString("AddPolicyCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Policy..
        /// </summary>
        internal static string AddPolicyCommandTextLong {
            get {
                return ResourceManager.GetString("AddPolicyCommandTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Injection Application Block.
        /// </summary>
        internal static string AddPolicyInjectionSettingsCommandText {
            get {
                return ResourceManager.GetString("AddPolicyInjectionSettingsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the Policy Injection Application Block..
        /// </summary>
        internal static string AddPolicyInjectionSettingsCommandTextLong {
            get {
                return ResourceManager.GetString("AddPolicyInjectionSettingsCommandTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Matching Rule.
        /// </summary>
        internal static string AddPropertyMatchingRuleCommandText {
            get {
                return ResourceManager.GetString("AddPropertyMatchingRuleCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Property Matching Rule..
        /// </summary>
        internal static string AddPropertyMatchingRuleCommandTextLong {
            get {
                return ResourceManager.GetString("AddPropertyMatchingRuleCommandTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remoting Policy Injector.
        /// </summary>
        internal static string AddRemotingInjectorCommandText {
            get {
                return ResourceManager.GetString("AddRemotingInjectorCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remoting Policy Injector.
        /// </summary>
        internal static string AddRemotingInjectorCommandTextLong {
            get {
                return ResourceManager.GetString("AddRemotingInjectorCommandTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Type Matching Rule.
        /// </summary>
        internal static string AddReturnTypeMatchingRuleCommandText {
            get {
                return ResourceManager.GetString("AddReturnTypeMatchingRuleCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Return Type Matching Rule..
        /// </summary>
        internal static string AddReturnTypeMatchingRuleCommandTextLong {
            get {
                return ResourceManager.GetString("AddReturnTypeMatchingRuleCommandTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Matching Rule.
        /// </summary>
        internal static string AddTypeMatchingRuleCommandText {
            get {
                return ResourceManager.GetString("AddTypeMatchingRuleCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Type Matching Rule..
        /// </summary>
        internal static string AddTypeMatchingRuleTextLong {
            get {
                return ResourceManager.GetString("AddTypeMatchingRuleTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Matching Rule.
        /// </summary>
        internal static string AssemblyMatchingRule {
            get {
                return ResourceManager.GetString("AssemblyMatchingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly name to match in &apos;Name (Version=?) (Culture=?) (PublicKeyToken=?) &apos; -format..
        /// </summary>
        internal static string AssemblyNameDescription {
            get {
                return ResourceManager.GetString("AssemblyNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the attribute that should be used to match..
        /// </summary>
        internal static string AttributeTypeDescription {
            get {
                return ResourceManager.GetString("AttributeTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handlers.
        /// </summary>
        internal static string CallHandlersCollectionNodeName {
            get {
                return ResourceManager.GetString("CallHandlersCollectionNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string CategoryGeneral {
            get {
                return ResourceManager.GetString("CategoryGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Attribute Matching Rule.
        /// </summary>
        internal static string CustomAttributeMatchingRuleNodeName {
            get {
                return ResourceManager.GetString("CustomAttributeMatchingRuleNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Policy Injector.
        /// </summary>
        internal static string CustomInjectorNodeName {
            get {
                return ResourceManager.GetString("CustomInjectorNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Matching Rule.
        /// </summary>
        internal static string CustomMatchingRuleNodeName {
            get {
                return ResourceManager.GetString("CustomMatchingRuleNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The injector used to create policy-enabled objects.
        /// </summary>
        internal static string DefaultInjectorDescription {
            get {
                return ResourceManager.GetString("DefaultInjectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DefaultMatchingRuleAssemblyName {
            get {
                return ResourceManager.GetString("DefaultMatchingRuleAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DefaultMethodSignatureMatchValue {
            get {
                return ResourceManager.GetString("DefaultMethodSignatureMatchValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DefaultReturnTypeMatchValue {
            get {
                return ResourceManager.GetString("DefaultReturnTypeMatchValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DefaultTagValue {
            get {
                return ResourceManager.GetString("DefaultTagValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of injection methods available to use. This determines the default injector to use..
        /// </summary>
        internal static string InjectorCollectionNodeDescription {
            get {
                return ResourceManager.GetString("InjectorCollectionNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injectors.
        /// </summary>
        internal static string InjectorCollectionNodeName {
            get {
                return ResourceManager.GetString("InjectorCollectionNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the custom configuration attributes for this type..
        /// </summary>
        internal static string InjectorExtensionsDescription {
            get {
                return ResourceManager.GetString("InjectorExtensionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a class that derives from PolicyInjector..
        /// </summary>
        internal static string InjectorTypeNameDescription {
            get {
                return ResourceManager.GetString("InjectorTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of matches is empty..
        /// </summary>
        internal static string MatchDataCollectionEmpty {
            get {
                return ResourceManager.GetString("MatchDataCollectionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of matches contains a duplicate value..
        /// </summary>
        internal static string MatchDataContainsDuplicateMatch {
            get {
                return ResourceManager.GetString("MatchDataContainsDuplicateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of matches contains a match with empty value..
        /// </summary>
        internal static string MatchDataContainsEmptyMatch {
            get {
                return ResourceManager.GetString("MatchDataContainsEmptyMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching Rules.
        /// </summary>
        internal static string MatchingRuleCollectionNodeName {
            get {
                return ResourceManager.GetString("MatchingRuleCollectionNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of method names that are used to match..
        /// </summary>
        internal static string MemberNameMatchesDescription {
            get {
                return ResourceManager.GetString("MemberNameMatchesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Name Matching Rule.
        /// </summary>
        internal static string MemberNameMatchingRuleNodeName {
            get {
                return ResourceManager.GetString("MemberNameMatchingRuleNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True if matching the methods name should be done in a case-insensitive manner, otherwise false..
        /// </summary>
        internal static string MethodSignatureIgnoreCaseDescription {
            get {
                return ResourceManager.GetString("MethodSignatureIgnoreCaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the method that is used to match..
        /// </summary>
        internal static string MethodSignatureMatchDescription {
            get {
                return ResourceManager.GetString("MethodSignatureMatchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Signature Matching Rule.
        /// </summary>
        internal static string MethodSignatureMatchingRuleNodeName {
            get {
                return ResourceManager.GetString("MethodSignatureMatchingRuleNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify the default injector if any injectors are configured..
        /// </summary>
        internal static string MustHaveDefaultInjectorIfInjectorsAreDefined {
            get {
                return ResourceManager.GetString("MustHaveDefaultInjectorIfInjectorsAreDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of namespace names that are used to match..
        /// </summary>
        internal static string NamespaceMatchesDescription {
            get {
                return ResourceManager.GetString("NamespaceMatchesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace Matching Rule.
        /// </summary>
        internal static string NamespaceMatchingRuleNodeName {
            get {
                return ResourceManager.GetString("NamespaceMatchingRuleNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of parameter types contains a duplicate entry..
        /// </summary>
        internal static string ParameterTypeCollectionContainsDuplicateName {
            get {
                return ResourceManager.GetString("ParameterTypeCollectionContainsDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of parameter types contains an entry with an empty name..
        /// </summary>
        internal static string ParameterTypeCollectionContainsEmptyName {
            get {
                return ResourceManager.GetString("ParameterTypeCollectionContainsEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of parameter types contains an empty entry..
        /// </summary>
        internal static string ParameterTypeCollectionContainsEmptyType {
            get {
                return ResourceManager.GetString("ParameterTypeCollectionContainsEmptyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of parameters for the method to match..
        /// </summary>
        internal static string ParameterTypeMatchDescription {
            get {
                return ResourceManager.GetString("ParameterTypeMatchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Type Matching Rule.
        /// </summary>
        internal static string ParameterTypeMatchingRuleNodeName {
            get {
                return ResourceManager.GetString("ParameterTypeMatchingRuleNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of parameter types that should match the methods signature..
        /// </summary>
        internal static string ParameterTypesDescription {
            get {
                return ResourceManager.GetString("ParameterTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of  policies.
        /// </summary>
        internal static string PolicyCollectionNodeDescription {
            get {
                return ResourceManager.GetString("PolicyCollectionNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies.
        /// </summary>
        internal static string PolicyCollectionNodeName {
            get {
                return ResourceManager.GetString("PolicyCollectionNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Injection Application Block.
        /// </summary>
        internal static string PolicyInjectionSettingsNodeName {
            get {
                return ResourceManager.GetString("PolicyInjectionSettingsNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        internal static string PolicyNodeName {
            get {
                return ResourceManager.GetString("PolicyNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Matching Rule.
        /// </summary>
        internal static string PropertyMatchingRuleNodeName {
            get {
                return ResourceManager.GetString("PropertyMatchingRuleNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of property names to match the name of a property..
        /// </summary>
        internal static string PropertyRuleMatchesDescription {
            get {
                return ResourceManager.GetString("PropertyRuleMatchesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remoting Policy Injector.
        /// </summary>
        internal static string RemotingInjectorNodeName {
            get {
                return ResourceManager.GetString("RemotingInjectorNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True if matching the return value should be done in a case-insensitive manner, otherwise false..
        /// </summary>
        internal static string ReturnTypeIgnoreCaseDescription {
            get {
                return ResourceManager.GetString("ReturnTypeIgnoreCaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type name that should match a methods return type..
        /// </summary>
        internal static string ReturnTypeMatchDescription {
            get {
                return ResourceManager.GetString("ReturnTypeMatchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Type Matching Rule.
        /// </summary>
        internal static string ReturnTypeMatchingRuleNodeName {
            get {
                return ResourceManager.GetString("ReturnTypeMatchingRuleNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the custom configuration attributes for this type..
        /// </summary>
        internal static string RuleProviderExtensionsDescription {
            get {
                return ResourceManager.GetString("RuleProviderExtensionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a class that implements the IMatchingRule interface..
        /// </summary>
        internal static string RuleProviderTypeNameDescription {
            get {
                return ResourceManager.GetString("RuleProviderTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True if the inheritance chain of a method should be searched for the attribute to match, otherwise false..
        /// </summary>
        internal static string SearchInheritanceChainDescription {
            get {
                return ResourceManager.GetString("SearchInheritanceChainDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True if matching the tagvalue should be done in a case-insensitive manner, otherwise false..
        /// </summary>
        internal static string TagAttributeIgnoreCaseDescription {
            get {
                return ResourceManager.GetString("TagAttributeIgnoreCaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag attribute value to match..
        /// </summary>
        internal static string TagAttributeMatchDescription {
            get {
                return ResourceManager.GetString("TagAttributeMatchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Attribute Matching Rule.
        /// </summary>
        internal static string TagAttributeMatchingRuleCommandText {
            get {
                return ResourceManager.GetString("TagAttributeMatchingRuleCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tag Attribute Matching Rule..
        /// </summary>
        internal static string TagAttributeMatchingRuleCommandTextLong {
            get {
                return ResourceManager.GetString("TagAttributeMatchingRuleCommandTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Attribute Matching Rule.
        /// </summary>
        internal static string TagAttributeMatchingRuleNodeName {
            get {
                return ResourceManager.GetString("TagAttributeMatchingRuleNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of type names to match with the methods declaring type..
        /// </summary>
        internal static string TypeMatchesDescription {
            get {
                return ResourceManager.GetString("TypeMatchesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Matching Rule.
        /// </summary>
        internal static string TypeMatchingRuleNodeName {
            get {
                return ResourceManager.GetString("TypeMatchingRuleNodeName", resourceCulture);
            }
        }
    }
}
