//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.Security.Configuration.Manageability.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.Security.Configuration.Manageability.Proper" +
                            "ties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify settings for authorization provider &apos;{0}&apos;.
        /// </summary>
        internal static string AuthorizationProviderPolicyNameTemplate {
            get {
                return ResourceManager.GetString("AuthorizationProviderPolicyNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization providers.
        /// </summary>
        internal static string AuthorizationProvidersCategoryName {
            get {
                return ResourceManager.GetString("AuthorizationProvidersCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        internal static string AuthorizationRuleProviderRulesPartName {
            get {
                return ResourceManager.GetString("AuthorizationRuleProviderRulesPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify settings for security cache provider &apos;{0}&apos;.
        /// </summary>
        internal static string SecurityCacheProviderPolicyNameTemplate {
            get {
                return ResourceManager.GetString("SecurityCacheProviderPolicyNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security cache providers.
        /// </summary>
        internal static string SecurityCacheProvidersCategoryName {
            get {
                return ResourceManager.GetString("SecurityCacheProvidersCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string SecuritySectionCategoryName {
            get {
                return ResourceManager.GetString("SecuritySectionCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default authorization provider.
        /// </summary>
        internal static string SecuritySettingsDefaultAuthorizationProviderPartName {
            get {
                return ResourceManager.GetString("SecuritySettingsDefaultAuthorizationProviderPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default security cache provider.
        /// </summary>
        internal static string SecuritySettingsDefaultSecurityCacheProviderPartName {
            get {
                return ResourceManager.GetString("SecuritySettingsDefaultSecurityCacheProviderPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Security Block Settings.
        /// </summary>
        internal static string SecuritySettingsPolicyName {
            get {
                return ResourceManager.GetString("SecuritySettingsPolicyName", resourceCulture);
            }
        }
    }
}
