'===============================================================================
' Microsoft patterns & practices Enterprise Library
' Logging Application Block QuickStart
'===============================================================================
' Copyright © Microsoft Corporation.  All rights reserved.
' THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
' OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
' LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
' FITNESS FOR A PARTICULAR PURPOSE.
'===============================================================================

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LoggingQuickStart.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This scenario demonstrates how to determine if an event will be logged based upon the configured filters..
        '''</summary>
        Friend ReadOnly Property CheckFilterStartMessage() As String
            Get
                Return ResourceManager.GetString("CheckFilterStartMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The quick start has logged an event by using a custom trace listener. Please check on the debugger&apos;s output for more details on the logged event..
        '''</summary>
        Friend ReadOnly Property CustomizedSinkEndMessage() As String
            Get
                Return ResourceManager.GetString("CustomizedSinkEndMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The scenario logs information to a custom trace listener. .
        '''</summary>
        Friend ReadOnly Property CustomizedSinkStartMessage() As String
            Get
                Return ResourceManager.GetString("CustomizedSinkStartMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Event logged by Debug Sink:
        '''	Event ID: {0}
        '''	Message: &quot;{1}&quot;..
        '''</summary>
        Friend ReadOnly Property DebugSinkMessage() As String
            Get
                Return ResourceManager.GetString("DebugSinkMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This message should be displayed by the debugger..
        '''</summary>
        Friend ReadOnly Property DebugSinkTestMessage() As String
            Get
                Return ResourceManager.GetString("DebugSinkTestMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The category &quot;General&quot; sends log information to the event log by default. Please go to event viewer to see the logged information..
        '''</summary>
        Friend ReadOnly Property DefaultCategoryMessage() As String
            Get
                Return ResourceManager.GetString("DefaultCategoryMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The event with EventId {0} has been processed by the Logging and Instrumentation Application Block.
        '''
        '''The default QuickStart configuration includes listeners to log event information to the application event log, the trace.log text file, and the Visual Studio Output Window. .
        '''</summary>
        Friend ReadOnly Property EventProcessedMessage() As String
            Get
                Return ResourceManager.GetString("EventProcessedMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Quick Start has finished logging the extra information. The default configuration of the Quick Starts sends the entries to the event log..
        '''</summary>
        Friend ReadOnly Property ExtraInformationEndMessage() As String
            Get
                Return ResourceManager.GetString("ExtraInformationEndMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This scenario is logging extra information to the destination specified by the default category. .
        '''</summary>
        Friend ReadOnly Property ExtraInformationStartMessage() As String
            Get
                Return ResourceManager.GetString("ExtraInformationStartMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A category is required.
        '''</summary>
        Friend ReadOnly Property InvalidCategoryMessage() As String
            Get
                Return ResourceManager.GetString("InvalidCategoryMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have entered some invalid information. Please correct the following before proceeding:
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property InvalidDataMessage() As String
            Get
                Return ResourceManager.GetString("InvalidDataMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Event ID must be numeric
        '''.
        '''</summary>
        Friend ReadOnly Property InvalidEventIDMessage() As String
            Get
                Return ResourceManager.GetString("InvalidEventIDMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Priority must be numeric
        '''.
        '''</summary>
        Friend ReadOnly Property InvalidPriorityMessage() As String
            Get
                Return ResourceManager.GetString("InvalidPriorityMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The following log entry information will be submitted to the Logging and Instrumentation Application Block:
        '''
        '''{0}.
        '''</summary>
        Friend ReadOnly Property LogEventStartMessage() As String
            Get
                Return ResourceManager.GetString("LogEventStartMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Logging Application Block Quick Start.
        '''</summary>
        Friend ReadOnly Property QuickStartTitleMessage() As String
            Get
                Return ResourceManager.GetString("QuickStartTitleMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sink failed because: {0}..
        '''</summary>
        Friend ReadOnly Property SinkFailureMessage() As String
            Get
                Return ResourceManager.GetString("SinkFailureMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Quick Start has finished executing the tracing scenario. The default configuration of the Quick Starts sends the trace messages to the flat file sink and logs the troubleshooting message to the event log. Please examine the file {0} for the trace information..
        '''</summary>
        Friend ReadOnly Property TraceDoneMessage() As String
            Get
                Return ResourceManager.GetString("TraceDoneMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Quick Start is using the Tracer class to trace activities and log context information. The following call stack will be traced:
        '''
        '''  traceButton_Click
        '''      DoDataAccess
        '''          DoTroubleshooting
        '''.
        '''</summary>
        Friend ReadOnly Property TraceStartMessage() As String
            Get
                Return ResourceManager.GetString("TraceStartMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The category &quot;Trace&quot; sends log information to the file {0} by default. Please examine this file to see if the information was logged..
        '''</summary>
        Friend ReadOnly Property TracingCategoryMessage() As String
            Get
                Return ResourceManager.GetString("TracingCategoryMessage", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
