//===============================================================================
// Microsoft patterns & practices Enterprise Library
// Caching Application Block
//===============================================================================
// Copyright © Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===============================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.Caching.Cryptography.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DesignResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesignResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.Caching.Cryptography.Configuration.DesignRe" +
                            "sources", typeof(DesignResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypts the data in the backing store (but not in memory) using a Symmetric Cryptography Provider defined in the Cryptography Application Block..
        /// </summary>
        internal static string SymmetricStorageEncryptionProviderDataDescription {
            get {
                return ResourceManager.GetString("SymmetricStorageEncryptionProviderDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetric Crypto Provider.
        /// </summary>
        internal static string SymmetricStorageEncryptionProviderDataDisplayName {
            get {
                return ResourceManager.GetString("SymmetricStorageEncryptionProviderDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Symmetric Cryptography Provider..
        /// </summary>
        internal static string SymmetricStorageEncryptionProviderDataNameDescription {
            get {
                return ResourceManager.GetString("SymmetricStorageEncryptionProviderDataNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SymmetricStorageEncryptionProviderDataNameDisplayName {
            get {
                return ResourceManager.GetString("SymmetricStorageEncryptionProviderDataNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Symmetric Cryptography Provider to use, as configured in the settings for the Cryptography Application Block..
        /// </summary>
        internal static string SymmetricStorageEncryptionProviderDataSymmetricInstanceDescription {
            get {
                return ResourceManager.GetString("SymmetricStorageEncryptionProviderDataSymmetricInstanceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetric Crypto Provider.
        /// </summary>
        internal static string SymmetricStorageEncryptionProviderDataSymmetricInstanceDisplayName {
            get {
                return ResourceManager.GetString("SymmetricStorageEncryptionProviderDataSymmetricInstanceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified type name of the Symmetric Cryptography Provider..
        /// </summary>
        internal static string SymmetricStorageEncryptionProviderDataTypeNameDescription {
            get {
                return ResourceManager.GetString("SymmetricStorageEncryptionProviderDataTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name.
        /// </summary>
        internal static string SymmetricStorageEncryptionProviderDataTypeNameDisplayName {
            get {
                return ResourceManager.GetString("SymmetricStorageEncryptionProviderDataTypeNameDisplayName", resourceCulture);
            }
        }
    }
}
