//===============================================================================
// Microsoft patterns & practices Enterprise Library
// Core
//===============================================================================
// Copyright © Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===============================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.Configuration.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.Configuration.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load assembly &apos;{0}&apos;. Please copy the assembly file to the tools rundirectory at &apos;{1}&apos; and reload the configuration..
        /// </summary>
        internal static string AssemblyResolveFailed {
            get {
                return ResourceManager.GetString("AssemblyResolveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string CaptionError {
            get {
                return ResourceManager.GetString("CaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Files(web.config, *.exe.config, app.config)|web.config;*.exe.config;app.config|All Files(*.*)|*.*..
        /// </summary>
        internal static string ConfigurationFileFilter {
            get {
                return ResourceManager.GetString("ConfigurationFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string DefaultStatusBarText {
            get {
                return ResourceManager.GetString("DefaultStatusBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save {0}..
        /// </summary>
        internal static string InvalidSaveHierarchyMessage {
            get {
                return ResourceManager.GetString("InvalidSaveHierarchyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new configuration application.
        /// </summary>
        internal static string NewApplicationStatusBarText {
            get {
                return ResourceManager.GetString("NewApplicationStatusBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Label Edit.
        /// </summary>
        internal static string NodeLabelEditCaption {
            get {
                return ResourceManager.GetString("NodeLabelEditCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to rename the TreeNode -&gt; .
        /// </summary>
        internal static string NodeLabelEditFailedText {
            get {
                return ResourceManager.GetString("NodeLabelEditFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tree node label.
        ///The label cannot be blank..
        /// </summary>
        internal static string NodeLabelEditText {
            get {
                return ResourceManager.GetString("NodeLabelEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an existing configuration application.
        /// </summary>
        internal static string OpenApplicationStatusBarText {
            get {
                return ResourceManager.GetString("OpenApplicationStatusBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all the application configuration.
        /// </summary>
        internal static string SaveAllStatusBarText {
            get {
                return ResourceManager.GetString("SaveAllStatusBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Application.
        /// </summary>
        internal static string SaveApplicationCaption {
            get {
                return ResourceManager.GetString("SaveApplicationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the applications could not be saved. Please correct the errors and try again..
        /// </summary>
        internal static string SaveApplicationsMessage {
            get {
                return ResourceManager.GetString("SaveApplicationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current application configuration..
        /// </summary>
        internal static string SaveApplicationStatusBarText {
            get {
                return ResourceManager.GetString("SaveApplicationStatusBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current application in another file..
        /// </summary>
        internal static string SaveAsApplicationStatusBarText {
            get {
                return ResourceManager.GetString("SaveAsApplicationStatusBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string SaveAsDialogTitle {
            get {
                return ResourceManager.GetString("SaveAsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load type &apos;{0}&apos;. Please copy the assembly that contains this type to the tools rundirectory at &apos;{1}&apos; and reload the configuration..
        /// </summary>
        internal static string TypeResolveFailed {
            get {
                return ResourceManager.GetString("TypeResolveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception.
        /// </summary>
        internal static string UnhandledExceptionFormText {
            get {
                return ResourceManager.GetString("UnhandledExceptionFormText", resourceCulture);
            }
        }
    }
}
