//===============================================================================
// Microsoft patterns & practices Enterprise Library
// Security Application Block
//===============================================================================
// Copyright © Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===============================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.Security.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.Security.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Rule Expression.
        /// </summary>
        internal static string AddAuthorizationRuleData {
            get {
                return ResourceManager.GetString("AddAuthorizationRuleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an authorization rule expression that defines when the rule takes effect..
        /// </summary>
        internal static string AddAuthorizationRuleDataDescription {
            get {
                return ResourceManager.GetString("AddAuthorizationRuleDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Rule.
        /// </summary>
        internal static string AddAuthorizationRuleProviderData {
            get {
                return ResourceManager.GetString("AddAuthorizationRuleProviderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a new Authorization Rule provider..
        /// </summary>
        internal static string AddAuthorizationRuleProviderDataDescription {
            get {
                return ResourceManager.GetString("AddAuthorizationRuleProviderDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string AddCustomAuthorizationProviderData {
            get {
                return ResourceManager.GetString("AddCustomAuthorizationProviderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a custom authorization provider by selecting its type..
        /// </summary>
        internal static string AddCustomAuthorizationProviderDataDescription {
            get {
                return ResourceManager.GetString("AddCustomAuthorizationProviderDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Requests Denied/sec is the rate at which authorization requests where denied..
        /// </summary>
        internal static string AuthorizationCheckFailedHelpResource {
            get {
                return ResourceManager.GetString("AuthorizationCheckFailedHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Requests/sec is the rate at which authorization requests were received..
        /// </summary>
        internal static string AuthorizationCheckPerformedHelpResource {
            get {
                return ResourceManager.GetString("AuthorizationCheckPerformedHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization failed.
        /// </summary>
        internal static string AuthorizationFailed {
            get {
                return ResourceManager.GetString("AuthorizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        internal static string AuthorizationProvidersDisplayName {
            get {
                return ResourceManager.GetString("AuthorizationProvidersDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization rule {0} not found in configuration..
        /// </summary>
        internal static string AuthorizationRuleNotFoundMsg {
            get {
                return ResourceManager.GetString("AuthorizationRuleNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to curity Application Block.
        /// </summary>
        internal static string BlockName {
            get {
                return ResourceManager.GetString("BlockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error occurred retrieving the configuration for authorization provider instance &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorAuthorizationConfigurationFailedMessage {
            get {
                return ResourceManager.GetString("ErrorAuthorizationConfigurationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error occurred retrieving the configuration for security cache provider instance &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorSecurityCacheConfigurationFailedMessage {
            get {
                return ResourceManager.GetString("ErrorSecurityCacheConfigurationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication provider named &apos;{0}&apos; could not be found in configuration..
        /// </summary>
        internal static string ExceptionAuthenticationProviderNotFound {
            get {
                return ResourceManager.GetString("ExceptionAuthenticationProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authorization provider named &apos;{0}&apos; could not be found in configuration..
        /// </summary>
        internal static string ExceptionAuthorizationProviderNotFound {
            get {
                return ResourceManager.GetString("ExceptionAuthorizationProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be implemented by subclasses..
        /// </summary>
        internal static string ExceptionMustBeImplementedBySubclass {
            get {
                return ResourceManager.GetString("ExceptionMustBeImplementedBySubclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter must implement type &apos;{0}&apos;..
        /// </summary>
        internal static string ExceptionParameterMustImplementType {
            get {
                return ResourceManager.GetString("ExceptionParameterMustImplementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile provider named &apos;{0}&apos; could not be found in configuration..
        /// </summary>
        internal static string ExceptionProfileProviderNotFound {
            get {
                return ResourceManager.GetString("ExceptionProfileProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The roles provider named &apos;{0}&apos; could not be found in configuration..
        /// </summary>
        internal static string ExceptionRolesProviderNotFound {
            get {
                return ResourceManager.GetString("ExceptionRolesProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The security cache provider named &apos;{0}&apos; could not be found in configuration..
        /// </summary>
        internal static string ExceptionSecurityCacheProviderNotFound {
            get {
                return ResourceManager.GetString("ExceptionSecurityCacheProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Custom Authentication Provider &apos;{0}&apos; with Type &apos;{1}&apos; must derive from IAuthorizationProvider.
        /// </summary>
        internal static string ExceptionTypeForCustomAuthProviderMustDeriveFrom {
            get {
                return ResourceManager.GetString("ExceptionTypeForCustomAuthProviderMustDeriveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Custom Security Cache Provider &apos;{0}&apos; with Type &apos;{1}&apos; must derive from ISecurityCacheProvider.
        /// </summary>
        internal static string ExceptionTypeForCustomCacheProviderMustDeriveFrom {
            get {
                return ResourceManager.GetString("ExceptionTypeForCustomCacheProviderMustDeriveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided IIdentity object is incomplete or invalid..
        /// </summary>
        internal static string IdentityInvalid {
            get {
                return ResourceManager.GetString("IdentityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided IIdentity object is null..
        /// </summary>
        internal static string IdentityIsNull {
            get {
                return ResourceManager.GetString("IdentityIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;securityConfiguration&quot; section is not available in the supplied configuration source..
        /// </summary>
        internal static string MissingSection {
            get {
                return ResourceManager.GetString("MissingSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no default authorization provider defined in the &quot;securityConfiguration&quot; section available in the supplied configuration source..
        /// </summary>
        internal static string NoDefaultAuthorizationProvider {
            get {
                return ResourceManager.GetString("NoDefaultAuthorizationProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no default security cache provider defined in the &quot;securityConfiguration&quot; section available in the supplied configuration source..
        /// </summary>
        internal static string NoDefaultSecurityCacheProvider {
            get {
                return ResourceManager.GetString("NoDefaultSecurityCacheProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Cache.
        /// </summary>
        internal static string SecurityCacheProvidersDisplayName {
            get {
                return ResourceManager.GetString("SecurityCacheProvidersDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Cache Reads/sec is the rate at which security cache reads were requested..
        /// </summary>
        internal static string SecurityCacheReadPerformedHelpResource {
            get {
                return ResourceManager.GetString("SecurityCacheReadPerformedHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Application Block.
        /// </summary>
        internal static string SecuritySettingsDisplayName {
            get {
                return ResourceManager.GetString("SecuritySettingsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Authorization Requests Denied is the total number of authorization requests denied..
        /// </summary>
        internal static string TotalAuthorizationCheckFailedHelpResource {
            get {
                return ResourceManager.GetString("TotalAuthorizationCheckFailedHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Authorization Requests is the total number of authorization requests received..
        /// </summary>
        internal static string TotalAuthorizationCheckPerformedHelpResource {
            get {
                return ResourceManager.GetString("TotalAuthorizationCheckPerformedHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Security Cache Reads is the total number of security cache reads requested..
        /// </summary>
        internal static string TotalSecurityCacheReadPerformedHelpResource {
            get {
                return ResourceManager.GetString("TotalSecurityCacheReadPerformedHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found token &quot;{1}&quot; when expecting {0} at position {2}..
        /// </summary>
        internal static string UnexpectedTokenMessage {
            get {
                return ResourceManager.GetString("UnexpectedTokenMessage", resourceCulture);
            }
        }
    }
}
