//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.Configuration.Manageability.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.Configuration.Manageabili" +
                            "ty.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string CustomHandlerAttributesPartName {
            get {
                return ResourceManager.GetString("CustomHandlerAttributesPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string CustomHandlerTypePartName {
            get {
                return ResourceManager.GetString("CustomHandlerTypePartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handlers.
        /// </summary>
        internal static string ExceptionTypeHandlersPartName {
            get {
                return ResourceManager.GetString("ExceptionTypeHandlersPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify settings for exception type &apos;{0}&apos;.
        /// </summary>
        internal static string ExceptionTypePolicyNameTemplate {
            get {
                return ResourceManager.GetString("ExceptionTypePolicyNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post handling action.
        /// </summary>
        internal static string ExceptionTypePostHandlingActionPartName {
            get {
                return ResourceManager.GetString("ExceptionTypePostHandlingActionPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler: &apos;{0}&apos;.
        /// </summary>
        internal static string HandlerPartNameTemplate {
            get {
                return ResourceManager.GetString("HandlerPartNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception message.
        /// </summary>
        internal static string ReplaceHandlerExceptionMessagePartName {
            get {
                return ResourceManager.GetString("ReplaceHandlerExceptionMessagePartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception type.
        /// </summary>
        internal static string ReplaceHandlerExceptionTypePartName {
            get {
                return ResourceManager.GetString("ReplaceHandlerExceptionTypePartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception handling.
        /// </summary>
        internal static string SectionCategoryName {
            get {
                return ResourceManager.GetString("SectionCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify settings for the Exception Handling Application Block.
        /// </summary>
        internal static string SectionPolicyName {
            get {
                return ResourceManager.GetString("SectionPolicyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception message.
        /// </summary>
        internal static string WrapHandlerExceptionMessagePartName {
            get {
                return ResourceManager.GetString("WrapHandlerExceptionMessagePartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception type.
        /// </summary>
        internal static string WrapHandlerExceptionTypePartName {
            get {
                return ResourceManager.GetString("WrapHandlerExceptionTypePartName", resourceCulture);
            }
        }
    }
}
