//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.PolicyInjection.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.PolicyInjection.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The match was not set for assembly matching rule {0}..
        /// </summary>
        internal static string ErrorAssemblyMatchingRuleMatchNotSet {
            get {
                return ResourceManager.GetString("ErrorAssemblyMatchingRuleMatchNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute type name was not set for custom attribute matching rule {0}..
        /// </summary>
        internal static string ErrorAttributeTypeNameNotSet {
            get {
                return ResourceManager.GetString("ErrorAttributeTypeNameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the matches was not set for member name matching rule {0}..
        /// </summary>
        internal static string ErrorMemberNameMatchingRuleMatchNotSet {
            get {
                return ResourceManager.GetString("ErrorMemberNameMatchingRuleMatchNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The match was not set for method signature matching rule {0}..
        /// </summary>
        internal static string ErrorMethodSignatureMatchingRuleMatchNotSet {
            get {
                return ResourceManager.GetString("ErrorMethodSignatureMatchingRuleMatchNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the matches was not set for namespace matching rule {0}..
        /// </summary>
        internal static string ErrorNamespaceMatchingRuleMatchNotSet {
            get {
                return ResourceManager.GetString("ErrorNamespaceMatchingRuleMatchNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the match was not set for parameter type matching rule {0}..
        /// </summary>
        internal static string ErrorParameterTypeMatchingRuleMatchNotSet {
            get {
                return ResourceManager.GetString("ErrorParameterTypeMatchingRuleMatchNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter type name was not set for parameter type element {0} of method signature matching rule {1}..
        /// </summary>
        internal static string ErrorParameterTypeNameNotSet {
            get {
                return ResourceManager.GetString("ErrorParameterTypeNameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The policy name was not set..
        /// </summary>
        internal static string ErrorPolicyNameNotSet {
            get {
                return ResourceManager.GetString("ErrorPolicyNameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the matches was not set for property matching rule {0}..
        /// </summary>
        internal static string ErrorPropertyMatchingRuleMatchNotSet {
            get {
                return ResourceManager.GetString("ErrorPropertyMatchingRuleMatchNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The return type was not set for return type matching rule {0}..
        /// </summary>
        internal static string ErrorReturnTypeMatchingRuleMatchNotSet {
            get {
                return ResourceManager.GetString("ErrorReturnTypeMatchingRuleMatchNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag attribute name was not set for tag attribute matching rule {0}..
        /// </summary>
        internal static string ErrorTagAttributeMatchingRuleMatchNotSet {
            get {
                return ResourceManager.GetString("ErrorTagAttributeMatchingRuleMatchNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the matches was not set for type matching rule {0}..
        /// </summary>
        internal static string ErrorTypeMatchingRuleMatchNotSet {
            get {
                return ResourceManager.GetString("ErrorTypeMatchingRuleMatchNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This rule is not intended to be used directly. Use the rules from the Microsoft.Practices.Unity.Interception assembly instead..
        /// </summary>
        internal static string PlaceholderRule {
            get {
                return ResourceManager.GetString("PlaceholderRule", resourceCulture);
            }
        }
    }
}
