//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.Data.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.Data.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise Library Data Service.
        /// </summary>
        internal static string CounterCategory {
            get {
                return ResourceManager.GetString("CounterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update row .
        /// </summary>
        internal static string ExceptionMessageUpdateDataSetRowFailure {
            get {
                return ResourceManager.GetString("ExceptionMessageUpdateDataSetRowFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Command Failures/Sec.
        /// </summary>
        internal static string NumCmdsFailPerSec {
            get {
                return ResourceManager.GetString("NumCmdsFailPerSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Commands Executed/Sec.
        /// </summary>
        internal static string NumCmdsPerSec {
            get {
                return ResourceManager.GetString("NumCmdsPerSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Connection Failures/Sec.
        /// </summary>
        internal static string NumConnFailPerSec {
            get {
                return ResourceManager.GetString("NumConnFailPerSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Connections Opened/Sec.
        /// </summary>
        internal static string NumConnPerSec {
            get {
                return ResourceManager.GetString("NumConnPerSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Transactions Aborted/Sec.
        /// </summary>
        internal static string NumTransAbortPerSec {
            get {
                return ResourceManager.GetString("NumTransAbortPerSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Transactions Committed/Sec.
        /// </summary>
        internal static string NumTransCommitPerSec {
            get {
                return ResourceManager.GetString("NumTransCommitPerSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Transaction Failures/Sec.
        /// </summary>
        internal static string NumTransFailPerSec {
            get {
                return ResourceManager.GetString("NumTransFailPerSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Transactions Opened/Sec.
        /// </summary>
        internal static string NumTransOpenPerSec {
            get {
                return ResourceManager.GetString("NumTransOpenPerSec", resourceCulture);
            }
        }
    }
}
