//===============================================================================
// Microsoft patterns & practices Enterprise Library
// SQL Configuration Source QuickStart
//===============================================================================
// Copyright © Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===============================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.SqlConfigurationSource.Design.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.SqlConfigurationSource.Design.Properties.Re" +
                            "sources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string CategoryGeneral {
            get {
                return ResourceManager.GetString("CategoryGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sql Settings.
        /// </summary>
        internal static string CategorySql {
            get {
                return ResourceManager.GetString("CategorySql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the Sql Configuration source element..
        /// </summary>
        internal static string SqlConfigurationSourceUICommandLongText {
            get {
                return ResourceManager.GetString("SqlConfigurationSourceUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sql Configuration Source.
        /// </summary>
        internal static string SqlConfigurationSourceUICommandText {
            get {
                return ResourceManager.GetString("SqlConfigurationSourceUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectionstring for connecting to the Microsoft SQL Server database.
        /// </summary>
        internal static string SqlConnectionStringDescription {
            get {
                return ResourceManager.GetString("SqlConnectionStringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the stored procedure to use for retrieving the configuration data.
        /// </summary>
        internal static string SqlGetSProcDescription {
            get {
                return ResourceManager.GetString("SqlGetSProcDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the stored procedure to use for refreshing the configuration data.
        /// </summary>
        internal static string SqlRefreshSProcDescription {
            get {
                return ResourceManager.GetString("SqlRefreshSProcDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the stored procedure to use for removing configuration data.
        /// </summary>
        internal static string SqlRemoveSprocDescription {
            get {
                return ResourceManager.GetString("SqlRemoveSprocDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the stored procedure to use for saving the configuration data.
        /// </summary>
        internal static string SqlSetSProcDescription {
            get {
                return ResourceManager.GetString("SqlSetSProcDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the type for the element..
        /// </summary>
        internal static string TypeNameDescription {
            get {
                return ResourceManager.GetString("TypeNameDescription", resourceCulture);
            }
        }
    }
}
