<?xml version="1.0" encoding="utf-8"?><Database Name="Logging" Class="LoggingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;Initial Catalog=Logging;Integrated Security=True" SettingsObjectName="aExpense.AutomationTests.Properties.Settings" SettingsPropertyName="LoggingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Association Name="Category_CategoryLog" Member="CategoryLogs" ThisKey="CategoryID" OtherKey="CategoryID" Type="CategoryLog" />
    </Type>
  </Table>
  <Table Name="dbo.CategoryLog" Member="CategoryLogs">
    <Type Name="CategoryLog">
      <Column Name="CategoryLogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LogID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Category_CategoryLog" Member="Category" ThisKey="CategoryID" OtherKey="CategoryID" Type="Category" IsForeignKey="true" />
      <Association Name="Log_CategoryLog" Member="Log" ThisKey="LogID" OtherKey="LogID" Type="Log" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Log]" Member="Logs">
    <Type Name="Log">
      <Column Name="LogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EventID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Severity" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MachineName" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="AppDomainName" Type="System.String" DbType="NVarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="ProcessID" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ProcessName" Type="System.String" DbType="NVarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="ThreadName" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Win32ThreadId" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="FormattedMessage" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Log_CategoryLog" Member="CategoryLogs" ThisKey="LogID" OtherKey="LogID" Type="CategoryLog" />
    </Type>
  </Table>
</Database>