//===============================================================================
// Microsoft patterns & practices Enterprise Library
// Policy Injection Application Block
//===============================================================================
// Copyright © Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===============================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.PolicyInjection.CallHandlers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.PolicyInjection.CallHandlers.Properties.Res" +
                            "ources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization failed.
        /// </summary>
        internal static string AuthorizationFailed {
            get {
                return ResourceManager.GetString("AuthorizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base counter used to calculate average call time..
        /// </summary>
        internal static string AverageCallDurationBaseCounterHelp {
            get {
                return ResourceManager.GetString("AverageCallDurationBaseCounterHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks the average length of time for a monitored method to complete..
        /// </summary>
        internal static string AverageCallDurationCounterHelp {
            get {
                return ResourceManager.GetString("AverageCallDurationCounterHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks calls / second to the monitored methods..
        /// </summary>
        internal static string CallsPerSecondCounterHelp {
            get {
                return ResourceManager.GetString("CallsPerSecondCounterHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot swallow exceptions for methods with non-null return type..
        /// </summary>
        internal static string CantSwallowNonVoidReturnMessage {
            get {
                return ResourceManager.GetString("CantSwallowNonVoidReturnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Logging.
        /// </summary>
        internal static string DefaultLogEntryTitle {
            get {
                return ResourceManager.GetString("DefaultLogEntryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Id to use when logging the call..
        /// </summary>
        internal static string EventIdDescription {
            get {
                return ResourceManager.GetString("EventIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks the number of exceptions / second thrown by the monitored methods..
        /// </summary>
        internal static string ExceptionsPerSecondCounterHelp {
            get {
                return ResourceManager.GetString("ExceptionsPerSecondCounterHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify the /category=&lt;name&gt;(;&lt;name&gt;) switch on the command line..
        /// </summary>
        internal static string NoCategoryErrorMessage {
            get {
                return ResourceManager.GetString("NoCategoryErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records the total number of calls to the monitored methods..
        /// </summary>
        internal static string NumberOfCallsCounterHelp {
            get {
                return ResourceManager.GetString("NumberOfCallsCounterHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records the total number of exceptions thrown by the monitored methods..
        /// </summary>
        internal static string NumberOfExceptionsCounterHelp {
            get {
                return ResourceManager.GetString("NumberOfExceptionsCounterHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance counters that are updated by the Policy Injection Application Block..
        /// </summary>
        internal static string PerformanceCounterCategoryHelp {
            get {
                return ResourceManager.GetString("PerformanceCounterCategoryHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter validation failed.
        /// </summary>
        internal static string ValidationFailedMessage {
            get {
                return ResourceManager.GetString("ValidationFailedMessage", resourceCulture);
            }
        }
    }
}
