//===============================================================================
// Microsoft patterns & practices Enterprise Library
// Exception Handling Application Block
//===============================================================================
// Copyright © Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===============================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.WCF.Configuration.Design.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.WCF.Configuration.Design." +
                            "Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add WCF.
        /// </summary>
        internal static string AddWCF {
            get {
                return ResourceManager.GetString("AddWCF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Message.
        /// </summary>
        internal static string ExceptionMessageDescription {
            get {
                return ResourceManager.GetString("ExceptionMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fault Contract Exception Handler.
        /// </summary>
        internal static string FaultContractExceptionHandlerNodeName {
            get {
                return ResourceManager.GetString("FaultContractExceptionHandlerNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Fault Contract Exception Handler..
        /// </summary>
        internal static string FaultContractExceptionHandlerNodeUICommandLongText {
            get {
                return ResourceManager.GetString("FaultContractExceptionHandlerNodeUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fault Contract Exception Handler.
        /// </summary>
        internal static string FaultContractExceptionHandlerNodeUICommandText {
            get {
                return ResourceManager.GetString("FaultContractExceptionHandlerNodeUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the fault contract property..
        /// </summary>
        internal static string FaultContractMappingNameDescription {
            get {
                return ResourceManager.GetString("FaultContractMappingNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the source exception property, or a GUID..
        /// </summary>
        internal static string FaultContractMappingSourceDescription {
            get {
                return ResourceManager.GetString("FaultContractMappingSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fault Contract.
        /// </summary>
        internal static string FaultContractTypeDescription {
            get {
                return ResourceManager.GetString("FaultContractTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property mappings collection has multiple entries for name {0}..
        /// </summary>
        internal static string PropertyMappingDuplicateNameError {
            get {
                return ResourceManager.GetString("PropertyMappingDuplicateNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} -&gt; {1}.
        /// </summary>
        internal static string PropertyMappingEditorFormat {
            get {
                return ResourceManager.GetString("PropertyMappingEditorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property mapping at position {0} has a null or empty name..
        /// </summary>
        internal static string PropertyMappingNameNullError {
            get {
                return ResourceManager.GetString("PropertyMappingNameNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property mappings.
        /// </summary>
        internal static string PropertyMappingsMessageDescription {
            get {
                return ResourceManager.GetString("PropertyMappingsMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCF.
        /// </summary>
        internal static string WCF {
            get {
                return ResourceManager.GetString("WCF", resourceCulture);
            }
        }
    }
}
