<?xml version="1.0" encoding="utf-8"?><Database Name="aExpense" Class="ExpensesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Expense" Member="Expenses">
    <Type Name="Expense">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Approved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CostCenter" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ReimbursementMethod" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Approver" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" />
      <Association Name="Expense_ExpenseDetail" Member="ExpenseDetails" ThisKey="Id" OtherKey="ExpenseId" Type="ExpenseDetail" />
    </Type>
  </Table>
  <Table Name="dbo.ExpenseDetail" Member="ExpenseDetails">
    <Type Name="ExpenseDetail">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ExpenseId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ReceiptThumbnailUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ReceiptUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Expense_ExpenseDetail" Member="Expense" ThisKey="ExpenseId" OtherKey="Id" Type="Expense" IsForeignKey="true" />
    </Type>
  </Table>
</Database>